---
- name:  [MySQL] Téléchargement paquet apt-config pour mysql.
  get_url:
      url="{{ mysql.url }}"
      dest=/opt/mysql.deb
      force=yes

- name:  [MySQL] Installation de MySQL apt config tool.
  apt:
      deb=/opt/mysql.deb

- name:  [MySQL] Installation de python-software-properties.
  apt:
    name=python-software-properties
    state=latest

- name:  [MySQL] Installation de MySQL et Librairies PHP/Python.
  apt:
    update_cache=yes
    name={{ item }}
    state=latest
  with_items:
      - mysql-community-server
      - php5-mysql
      - python-mysqldb
  notify:
    - restart mysql

- name:  [MySQL] Configuration de MySQL.
  template:
    src=mysql.cnf.j2
    dest=/etc/mysql/conf.d/mysql.cnf
  notify:
    - restart mysql

- name:  [MySQL] Ajout des crédits root dans /root/.my.cnf
  template:
    src=my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=600

- name:  [MySQL] Création des fichiers de logs.
  file:
      path=/var/log/mysqld.log
      owner=mysql
      state=touch

- name:  [MySQL] Démarrage de My_SQL.
  service:
      name=mysql
      state=started

- name:  [MySQL] Attente réponse BDD.
  wait_for:
    host="{{ ripper.host }}"
    port=3306
    delay=0
    timeout=300

- name:  [MySQL] Ajout compte root pour localhost.
  mysql_user:
    user=root
    password={{ mysql.root_pass }}
    host="{{ ripper.host }}"
  failed_when: false

- name:  [MySQL] Ajout compte root pour le FQDN.
  mysql_user:
    user="root"
    host="{{ ripper.host }}"
    password="{{ mysql.root_pass }}"
    login_user=root
    login_password="{{ mysql.root_pass }}"
    priv=*.*:ALL,GRANT


- name:  [MySQL] Suppression de l'user anonyme local.
  mysql_user:
    user=""
    state="absent"
    login_user=root
    login_password="{{ mysql.root_pass }}"

- name:  [MySQL] Suppression de l'user anonyme local.
  mysql_user:
    user=''
    host="{{ ansible_fqdn }}"
    state=absent
    login_user=root
    login_password="{{ mysql.root_pass }}"

- name:  [MySQL] Suppression de la Base test.
  mysql_db:
    db=test
    state=absent
    login_user=root
    login_password="{{ mysql.root_pass }}"

- name:  [MySQL] Démarrage du service My_SQL.
  service:
    name=mysql
    state=started
    enabled=yes
  changed_when: false
