# Création d'une image avec Ansible pré-installé.
FROM projetgl/jessie-mini:latest
RUN apt-get -y update
RUN apt-get install -y python-yaml python-jinja2 python-apt git time vim
RUN git clone http://github.com/ansible/ansible.git /opt/ansible
RUN apt-get clean autoclean
RUN apt-get autoremove -y
RUN echo "146.19.17.232     projetgl.lord.io" >> /etc/hosts
WORKDIR /opt/ansible
RUN git submodule update --init --recursive
ENV PATH /opt/ansible/bin:$PATH
ENV ANSIBLE_LIBRARY /opt/ansible/library
ENV PYTHONPATH /opt/ansible/lib:$PYTHON_PATH
ADD reaper /opt/reaper
# A partir des variables globales passées en argument, création des containers avec les ports qui vont bien.
{% set ports = [] -%}
{%- for p in ripper.containers %}
    {%- set _ = ports.append(p.ports.split(':') | first) -%}
{% endfor -%}
EXPOSE {{ " ".join(ports) }}
WORKDIR /opt/reaper
ENTRYPOINT ansible-playbook site.yml -e TARGET=$TARGET -c local -i hosts -vv & /bin/bash
CMD ["/bin/bash"]
